// Generated by Apple Swift version 3.1 (swiftlang-802.0.51 clang-802.0.41)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Dispatch;
@import UIKit;
@import CoreGraphics;
@import Foundation;
@import Security.CipherSuite;
#endif

#import <LiquidPlatformKit/LiquidPlatformKit.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class LDCBatchOperator;

SWIFT_CLASS_NAMED("BatchOperatorCollection")
@interface LDCBatchOperatorCollection : NSObject
- (LDCBatchOperator * _Nonnull)addOperator:(NSString * _Nonnull)name batchCount:(int32_t)batchCount queue:(dispatch_queue_t _Nonnull)queue batchHandler:(void (^ _Nonnull)(NSArray * _Nonnull))batchHandler SWIFT_WARN_UNUSED_RESULT;
- (void)add:(NSString * _Nonnull)name object:(id _Nonnull)object;
- (void)add:(NSString * _Nonnull)name object:(id _Nonnull)object count:(int32_t)count weight:(int32_t)weight;
- (void)forEach:(SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nonnull, LDCBatchOperator * _Nonnull))body;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LDKBreadCrumbView;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit24BreadCrumbViewDataSource_")
@protocol BreadCrumbViewDataSource
- (NSInteger)numberOfLabels:(LDKBreadCrumbView * _Nonnull)breadcrumbView SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)labelForIndex:(LDKBreadCrumbView * _Nonnull)breadcrumbView index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
@end

@class UIButton;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit22BreadCrumbViewDelegate_")
@protocol BreadCrumbViewDelegate
- (void)breadCrumbViewButtonPressed:(LDKBreadCrumbView * _Nonnull)breadCrumbView index:(NSInteger)index label:(NSString * _Nonnull)label button:(UIButton * _Nonnull)button;
@end

typedef SWIFT_ENUM(NSInteger, CellReplyMode) {
  CellReplyModeNone = 0,
  CellReplyModeReply = 1,
  CellReplyModeCancel = 2,
};

@class UICollectionViewLayoutAttributes;
@class NSCoder;

SWIFT_CLASS("_TtC17LiquidPlatformKit29CollectionViewWaterfallLayout")
@interface CollectionViewWaterfallLayout : UICollectionViewLayout
@property (nonatomic) NSInteger columnCount;
@property (nonatomic) float minimumColumnSpacing;
@property (nonatomic) float minimumInteritemSpacing;
@property (nonatomic) float headerHeight;
@property (nonatomic) float footerHeight;
@property (nonatomic) UIEdgeInsets headerInset;
@property (nonatomic) UIEdgeInsets footerInset;
@property (nonatomic) UIEdgeInsets sectionInset;
- (void)prepareLayout;
@property (nonatomic, readonly) CGSize collectionViewContentSize;
- (UICollectionViewLayoutAttributes * _Nullable)layoutAttributesForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewLayoutAttributes * _Nullable)layoutAttributesForSupplementaryViewOfKind:(NSString * _Nonnull)elementKind atIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (NSArray<UICollectionViewLayoutAttributes *> * _Nullable)layoutAttributesForElementsInRect:(CGRect)rect SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)newBounds SWIFT_WARN_UNUSED_RESULT;
- (void)invalidateLayout;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit37CollectionViewWaterfallLayoutDelegate_")
@protocol CollectionViewWaterfallLayoutDelegate <UICollectionViewDelegate>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)layout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@optional
- (float)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)layout heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (float)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)layout heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)layout insetForSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)layout insetForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)layout insetForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (float)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)layout minimumInteritemSpacingForSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit9Debouncer")
@interface Debouncer : NSObject
- (nonnull instancetype)initWithDelay:(double)delay callback:(void (^ _Nonnull)(id _Nullable))callback OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithThrottle:(double)delay callback:(void (^ _Nonnull)(id _Nullable))callback OBJC_DESIGNATED_INITIALIZER;
- (void)call:(id _Nullable)caller;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class NSBundle;

SWIFT_CLASS("_TtC17LiquidPlatformKit24DetailFormViewController")
@interface DetailFormViewController : UIViewController
@property (nonatomic, strong) UIViewController * _Nullable contentViewController;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)reloadData;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class LDMItem;

SWIFT_CLASS_NAMED("ExecuteInsightDecisions")
@interface ExecuteInsightDecisions : NSObject
+ (void)setFieldsFromOptions:(LDMItem * _Nullable)targetItem itemWithOptions:(LDMItem * _Nullable)itemWithOptions optionsFieldName:(NSString * _Nonnull)optionsFieldName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol LDKFilteredItemModelDelegate;

SWIFT_CLASS_NAMED("FilteredItemModel")
@interface LDKFilteredItemModel : NSObject
@property (nonatomic) BOOL enabled;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull updateFields;
@property (nonatomic, weak) id <LDKFilteredItemModelDelegate> _Nullable delegate;
- (void)fetchData;
- (void)destroy;
- (LDMItem * _Nonnull)itemAtIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSArray * _Nonnull array;
- (NSInteger)count SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class LDKHamburgerMenuViewController;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit24LDCHamburgerMenuDelegate_")
@protocol LDCHamburgerMenuDelegate
- (NSArray<LDMItem *> * _Nonnull)avalibleFunctionMaps:(LDKHamburgerMenuViewController * _Nonnull)menuViewController SWIFT_WARN_UNUSED_RESULT;
- (LDMItem * _Nullable)currentFunctionMap:(LDKHamburgerMenuViewController * _Nonnull)menuViewController SWIFT_WARN_UNUSED_RESULT;
- (void)selectFunctionMap:(LDKHamburgerMenuViewController * _Nonnull)menuViewController functionMap:(LDMItem * _Nonnull)functionMap;
- (NSArray<NSString *> * _Nullable)supportedPerspectives SWIFT_WARN_UNUSED_RESULT;
- (void)changePerspective:(NSString * _Nonnull)perspective;
@end

@class LDKNavigationViewController;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit27LDCNavigationCreateDelegate_")
@protocol LDCNavigationCreateDelegate
- (BOOL)createSupported SWIFT_WARN_UNUSED_RESULT;
- (void)createButtonPressed:(LDKNavigationViewController * _Nonnull)navigationViewController sender:(UIButton * _Nonnull)sender;
@end

@protocol LDKDetailForm;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit31LDCNavigationDetailFormDelegate_")
@protocol LDCNavigationDetailFormDelegate
- (id <LDKDetailForm> _Nullable)currentDetailForm SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit26LDCNavigationEventDelegate_")
@protocol LDCNavigationEventDelegate
@optional
- (void)backEvent;
- (void)willOpenRightDrawer:(UIViewController * _Nonnull)viewController animated:(BOOL)animated mode:(LDKDrawerMode)mode width:(CGFloat)width;
- (void)didOpenRightDrawer:(UIViewController * _Nonnull)viewController animated:(BOOL)animated mode:(LDKDrawerMode)mode width:(CGFloat)width;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit27LDCNavigationExportDelegate_")
@protocol LDCNavigationExportDelegate
- (BOOL)exportSupported SWIFT_WARN_UNUSED_RESULT;
- (void)exportButtonPressed:(LDKNavigationViewController * _Nonnull)navigationViewController sender:(UIButton * _Nonnull)sender;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit25LDCNavigationScanDelegate_")
@protocol LDCNavigationScanDelegate
- (BOOL)scanSupported SWIFT_WARN_UNUSED_RESULT;
- (void)scanButtonPressed:(LDKNavigationViewController * _Nonnull)navigationViewController sender:(UIButton * _Nonnull)sender;
@end

@class LDKSearchFilterViewController;
@class LDMSearch;
@class LDMQueryFilter;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit27LDCNavigationSearchDelegate_")
@protocol LDCNavigationSearchDelegate
- (NSDictionary<NSString *, id> * _Nullable)searchSupportedForConfig SWIFT_WARN_UNUSED_RESULT;
- (void)didSubmitSearch:(LDKNavigationViewController * _Nonnull)navigationViewController filterViewController:(LDKSearchFilterViewController * _Nonnull)filterViewController searchText:(NSString * _Nullable)searchText searchItem:(LDMSearch * _Nullable)searchItem queryFilter:(LDMQueryFilter * _Nullable)queryFilter;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit33LDCOffice365ConnectViewController")
@interface LDCOffice365ConnectViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIFont;
@class UIView;

SWIFT_CLASS("_TtC17LiquidPlatformKit25LDKAccordionSectionConfig")
@interface LDKAccordionSectionConfig : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) UIFont * _Nullable font;
@property (nonatomic, strong) UIView * _Nullable view;
@property (nonatomic) BOOL expanded;
@property (nonatomic) LDKAccordionSectionType type;
@property (nonatomic, strong) id _Nullable config;
@property (nonatomic, copy) NSString * _Nullable modeVisibility;
@property (nonatomic, copy) NSArray * _Nullable visibilityRules;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol LDKAccordionViewDataSource;
@protocol LDKAccordionViewDelegate;

SWIFT_CLASS("_TtC17LiquidPlatformKit16LDKAccordionView")
@interface LDKAccordionView : UIScrollView
@property (nonatomic, strong) id <LDKAccordionViewDataSource> _Nullable accordionDataSource;
@property (nonatomic, strong) id <LDKAccordionViewDelegate> _Nullable accordionDelegate;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)reloadData;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit26LDKAccordionViewDataSource_")
@protocol LDKAccordionViewDataSource
- (NSInteger)numberOfSections SWIFT_WARN_UNUSED_RESULT;
- (LDKAccordionSectionConfig * _Nonnull)configForSection:(NSInteger)_ SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit24LDKAccordionViewDelegate_")
@protocol LDKAccordionViewDelegate
- (void)didPressTitle:(NSInteger)idx;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit17LDKBreadCrumbView")
@interface LDKBreadCrumbView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
- (void)reloadData;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit15LDKCameraButton")
@interface LDKCameraButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit15LDKCreateButton")
@interface LDKCreateButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
- (void)layoutSubviews;
@end

@class LDKCalendarViewController;

SWIFT_CLASS_NAMED("LDKDateCalViewController")
@interface LDKDateCalViewController : UIViewController <LDKCalendarViewControllerDelegate>
@property (nonatomic, copy) NSDate * _Nullable date;
@property (nonatomic, copy) void (^ _Nullable didSelectDate)(LDKDateCalViewController * _Nonnull, NSDate * _Nonnull);
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)calendarViewConroller:(LDKCalendarViewController * _Null_unspecified)calendarViewController didSelectDate:(NSDate * _Null_unspecified)date initialLoad:(BOOL)initialFlag;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit13LDKDetailForm_")
@protocol LDKDetailForm
- (LDMItem * _Nullable)currentFunctionItem SWIFT_WARN_UNUSED_RESULT;
@end

@class NSLayoutManager;
@class UITextView;
@class NSTextAttachment;

SWIFT_CLASS("_TtC17LiquidPlatformKit33LDKDiscussionMessageTableViewCell")
@interface LDKDiscussionMessageTableViewCell : UITableViewCell <NSLayoutManagerDelegate, UITextViewDelegate>
@property (nonatomic) enum CellReplyMode replyMode;
@property (nonatomic) BOOL isSubMessage;
+ (CGFloat)cellHeightToFitMessage:(LDMItem * _Nonnull)message expanded:(BOOL)expanded showingDate:(BOOL)showingDate SWIFT_WARN_UNUSED_RESULT;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (void)setDiscussion:(LDMItem * _Nonnull)discussion expanded:(BOOL)expanded showingDate:(BOOL)showingDate;
- (void)update;
- (NSString * _Nonnull)initialsForUser:(LDMItem * _Nonnull)user SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)initialForUser:(LDMItem * _Nonnull)user field:(NSString * _Nonnull)field SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)layoutManager:(NSLayoutManager * _Nonnull)layoutManager lineSpacingAfterGlyphAtIndex:(NSInteger)glyphIndex withProposedLineFragmentRect:(CGRect)rect SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldInteractWithTextAttachment:(NSTextAttachment * _Nonnull)textAttachment inRange:(NSRange)characterRange SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldInteractWithURL:(NSURL * _Nonnull)URL inRange:(NSRange)characterRange SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit28LDKFilteredItemModelDelegate_")
@protocol LDKFilteredItemModelDelegate
- (void)didInsertItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)didRemoveItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)didUpdateItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
@optional
- (void)shouldScrollToIndex:(NSInteger)index;
@required
- (void)didUpdateData:(NSArray * _Nonnull)collectedData;
@end

@class NSMutableDictionary;
@class LDMSearchResults;
@class NSDictionary;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit20LDKInsightPopContent_")
@protocol LDKInsightPopContent
@property (nonatomic, strong) NSMutableDictionary * _Nullable options;
@property (nonatomic, readonly, strong) LDMItem * _Nullable selectedItem;
- (NSString * _Nullable)uniqueIdentifierForReportViewController:(id _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
- (void)reloadData;
- (void)report:(UIViewController * _Nonnull)viewController didUpdateSearchResults:(LDMSearchResults * _Nullable)searchResults;
- (void)report:(UIViewController * _Nonnull)viewcontroller willUpdateSearchResults:(void (^ _Nonnull)(LDMQueryFilter * _Nullable))callback;
- (void)report:(UIViewController * _Nonnull)viewController didUpdateSummaryResults:(NSDictionary * _Nullable)didUpdateSummaryResults;
- (void)report:(UIViewController * _Nonnull)viewController selectRowAtIndexPath:(NSIndexPath * _Nonnull)selectRowAtIndexPath;
- (void)reportViewControllerDidAddChild:(UIViewController * _Nonnull)parentViewController;
@end

@class UITableView;
@class UITableViewRowAction;
@class PHFComposeBarView;

SWIFT_CLASS_NAMED("LDKDiscussionViewController")
@interface LDKDiscussionViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, PHFComposeBarViewDelegate, LDKInsightPopContent, LDCNavigationEventDelegate, LDKFilteredItemModelDelegate>
@property (nonatomic, strong) LDMItem * _Nullable selectedItem;
@property (nonatomic, strong) NSMutableDictionary * _Nullable options;
- (nonnull instancetype)initWithItem:(LDMItem * _Nonnull)item OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)didInsertItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)didRemoveItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)didUpdateItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)shouldScrollToIndex:(NSInteger)index;
- (void)didUpdateData:(NSArray * _Nonnull)collectedData;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)tableView:(UITableView * _Nonnull)tableView canEditRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (NSArray<UITableViewRowAction *> * _Nullable)tableView:(UITableView * _Nonnull)tableView editActionsForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)tableView:(UITableView * _Nonnull)tableView shouldShowMenuForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)tableView:(UITableView * _Nonnull)tableView canPerformAction:(SEL _Nonnull)action forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Nullable)sender SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView performAction:(SEL _Nonnull)action forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Nullable)sender;
- (void)composeBarViewDidPressButton:(PHFComposeBarView * _Null_unspecified)composeBarView;
- (void)composeBarViewDidPressUtilityButton:(PHFComposeBarView * _Null_unspecified)composeBarView;
- (void)composeBarView:(PHFComposeBarView * _Null_unspecified)composeBarView willChangeFromFrame:(CGRect)startFrame toFrame:(CGRect)endFrame duration:(NSTimeInterval)duration animationCurve:(UIViewAnimationCurve)animationCurve;
- (void)didChangeText:(NSString * _Null_unspecified)text;
- (void)replyButtonPressed:(LDKDiscussionMessageTableViewCell * _Nonnull)cell discussion:(LDMItem * _Nullable)discussion sender:(UIButton * _Nonnull)sender replyMode:(enum CellReplyMode)replyMode;
- (void)textViewWasTapped:(LDKDiscussionMessageTableViewCell * _Nonnull)cell discussion:(LDMItem * _Nullable)discussion;
- (void)report:(UIViewController * _Nonnull)viewcontroller willUpdateSearchResults:(void (^ _Nonnull)(LDMQueryFilter * _Nullable))callback;
- (void)report:(UIViewController * _Nonnull)viewController selectRowAtIndexPath:(NSIndexPath * _Nonnull)selectRowAtIndexPath;
- (void)report:(UIViewController * _Nonnull)viewController didUpdateSummaryResults:(NSDictionary * _Nullable)didUpdateSummaryResults;
- (void)reportViewControllerDidAddChild:(UIViewController * _Nonnull)parentViewController;
- (NSString * _Nullable)uniqueIdentifierForReportViewController:(id _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
- (void)reloadData;
- (void)report:(UIViewController * _Nonnull)viewController didUpdateSearchResults:(LDMSearchResults * _Nullable)searchResults;
- (void)willOpenRightDrawer:(UIViewController * _Nonnull)viewController animated:(BOOL)animated mode:(LDKDrawerMode)mode width:(CGFloat)width;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class LDKFieldValueColumnView;
@class LDKFieldValueConfig;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit29LDKFieldValueColumnDataSource_")
@protocol LDKFieldValueColumnDataSource
- (NSInteger)numberOfColumns:(LDKFieldValueColumnView * _Nonnull)fieldValueView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)numberOfFields:(LDKFieldValueColumnView * _Nonnull)fieldValueView SWIFT_WARN_UNUSED_RESULT;
- (LDKFieldValueConfig * _Nonnull)configForField:(LDKFieldValueColumnView * _Nonnull)fieldValueView index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit27LDKFieldValueColumnDelegate_")
@protocol LDKFieldValueColumnDelegate
- (void)didChangeValue:(LDKFieldValueColumnView * _Nonnull)fieldValueView value:(id _Nullable)value index:(NSInteger)index;
- (void)performEdit:(LDKFieldValueColumnView * _Nonnull)fieldValueView sender:(UIButton * _Nonnull)sender index:(NSInteger)index;
@optional
- (void)didChangeFirstResponder:(LDKFieldValueColumnView * _Nonnull)fieldValueView firstResponder:(UIView * _Nullable)firstResponder;
@end

@class UIColor;
@class UITextField;

SWIFT_CLASS("_TtC17LiquidPlatformKit23LDKFieldValueColumnView")
@interface LDKFieldValueColumnView : UIView <UITextFieldDelegate>
@property (nonatomic, strong) UIColor * _Null_unspecified fieldLabelColor;
@property (nonatomic, strong) UIFont * _Null_unspecified fieldLabelFont;
@property (nonatomic, strong) UIColor * _Null_unspecified fieldLabelEditableColor;
@property (nonatomic, strong) UIFont * _Null_unspecified fieldLabelEditableFont;
@property (nonatomic, strong) UIColor * _Null_unspecified valueLabelColor;
@property (nonatomic, strong) UIFont * _Null_unspecified valueLabelFont;
@property (nonatomic, strong) UIColor * _Null_unspecified valueLabelEditableColor;
@property (nonatomic, strong) UIFont * _Null_unspecified valueLabelEditableFont;
@property (nonatomic) UIEdgeInsets fieldLabelInsets;
@property (nonatomic) UIEdgeInsets valueInsets;
@property (nonatomic) UIEdgeInsets fieldValueInsets;
@property (nonatomic) UIEdgeInsets edgeInsets;
@property (nonatomic, strong) id <LDKFieldValueColumnDataSource> _Nullable datasource;
@property (nonatomic, strong) id <LDKFieldValueColumnDelegate> _Nullable delegate;
@property (nonatomic) BOOL editing;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)reloadData;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end


@class UIBarButtonItem;
@class LDKEditDetailCollectionViewCell;

SWIFT_CLASS("_TtC17LiquidPlatformKit21LDKFormViewController")
@interface LDKFormViewController : UIViewController <LDKAccordionViewDataSource, LDKAccordionViewDelegate>
@property (nonatomic, strong) LDMItem * _Nullable form;
@property (nonatomic, strong) LDMItem * _Nullable originalItem;
@property (nonatomic) BOOL deleteButtonEnabled;
@property (nonatomic) BOOL transact;
@property (nonatomic) BOOL autoDismiss;
@property (nonatomic) BOOL autoEdit;
@property (nonatomic) BOOL executeCreateOptions;
@property (nonatomic, copy) NSString * _Nonnull transactionId;
@property (nonatomic, copy) NSDictionary<NSNumber *, NSNumber *> * _Nonnull heightNeededByIndex;
@property (nonatomic, copy) NSDictionary<NSNumber *, NSNumber *> * _Nonnull wasLoadedByIndex;
@property (nonatomic, copy) void (^ _Nullable didSave)(UIBarButtonItem * _Nonnull, LDMItem * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable didCancel)(UIBarButtonItem * _Nonnull, LDMItem * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable didDelete)(UIBarButtonItem * _Nonnull, LDMItem * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable didPressMenu)(UIButton * _Nonnull, LDMItem * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable shouldClose)(UIButton * _Nonnull, LDMItem * _Nonnull);
@property (nonatomic) LDKDrawerMode drawerMode;
@property (nonatomic) BOOL performLocalQueries;
@property (nonatomic, copy) NSString * _Nullable functionType;
@property (nonatomic, readonly) BOOL hasUnsavedChanges;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
@property (nonatomic, strong) LDMItem * _Nullable item;
@property (nonatomic) BOOL disableEdit;
- (void)reloadData:(BOOL)animate;
- (void)refresh;
- (void)reloadRow:(NSInteger)aIndex;
- (void)loadConfiguration:(LDMItem * _Nonnull)aForm;
- (void)setAllExpanded:(BOOL)expanded;
- (void)setEditing:(BOOL)editing animated:(BOOL)animated;
- (NSInteger)numberOfSections SWIFT_WARN_UNUSED_RESULT;
- (LDKAccordionSectionConfig * _Nonnull)configForSection:(NSInteger)idx SWIFT_WARN_UNUSED_RESULT;
- (void)didPressTitle:(NSInteger)idx;
- (void)collectionViewCell:(LDKEditDetailCollectionViewCell * _Nonnull)cell didModifyItem:(LDMItem * _Nonnull)item fields:(NSArray * _Nonnull)fields;
- (void)collectionViewCell:(LDKEditDetailCollectionViewCell * _Nonnull)cell didChangeFirstResponder:(UIView * _Nullable)firstResponder;
- (void)collectionViewCell:(LDKEditDetailCollectionViewCell * _Null_unspecified)cell didChangeSizeNeeded:(CGSize)sizeNeeded scroll:(BOOL)scroll;
@end


SWIFT_CLASS_NAMED("LDKHamburgerMenuViewController")
@interface LDKHamburgerMenuViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
+ (NSString * _Nonnull)cardPerspective SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)gridPerspective SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)mapPerspective SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)updateDelegateState;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@class UINavigationController;

SWIFT_CLASS("_TtC17LiquidPlatformKit24LDKMenuBarViewController")
@interface LDKMenuBarViewController : UIViewController <UINavigationControllerDelegate, BreadCrumbViewDelegate, BreadCrumbViewDataSource>
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)setDiscussionsBadgeText:(NSString * _Nullable)text;
- (void)setCreatable:(BOOL)creatable;
- (void)setSearchable:(BOOL)searchable;
- (void)setScanable:(BOOL)scanable;
- (void)setExportable:(BOOL)exportable;
- (void)setDiscussable:(BOOL)discussable;
- (void)reloadData;
- (void)navigationController:(UINavigationController * _Nonnull)navigationController willShowViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated;
- (void)breadCrumbViewButtonPressed:(LDKBreadCrumbView * _Nonnull)breadCrumbView index:(NSInteger)index label:(NSString * _Nonnull)label button:(UIButton * _Nonnull)button;
- (NSInteger)numberOfLabels:(LDKBreadCrumbView * _Nonnull)breadcrumbView SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)labelForIndex:(LDKBreadCrumbView * _Nonnull)breadcrumbView index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit29LDKModalWrapperViewController")
@interface LDKModalWrapperViewController : UIViewController
@property (nonatomic, strong) UIViewController * _Nullable contentViewController;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit23LDKNavigationController")
@interface LDKNavigationController : UINavigationController
@property (nonatomic, copy) NSArray<UIViewController *> * _Nonnull viewControllerHistory;
@property (nonatomic, readonly, strong) UIViewController * _Nullable topViewController;
@property (nonatomic, copy) NSArray<UIViewController *> * _Nonnull viewControllers;
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)didReceiveMemoryWarning;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@property (nonatomic, readonly) BOOL shouldAutorotate;
- (UIViewController * _Nullable)popViewControllerAnimated:(BOOL)animated SWIFT_WARN_UNUSED_RESULT;
- (NSArray<UIViewController *> * _Nullable)popToViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated SWIFT_WARN_UNUSED_RESULT;
- (NSArray<UIViewController *> * _Nullable)popToRootViewControllerAnimated:(BOOL)animated SWIFT_WARN_UNUSED_RESULT;
- (void)pushViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated;
- (void)setBreadCrumbLabel:(NSString * _Nonnull)label viewController:(UIViewController * _Nonnull)viewController;
- (void)removeBreadCrumbLabel:(UIViewController * _Nonnull)viewController;
- (NSString * _Nullable)breadCrumbLabelForIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)breadCrumbLabelForViewController:(UIViewController * _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)viewControllerForBreadCrumbLabel:(NSString * _Nonnull)breadCrumbLabel SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull identifiers;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit18LDKNavigationEntry_")
@protocol LDKNavigationEntry
@optional
- (BOOL)historyEntryUnique SWIFT_WARN_UNUSED_RESULT;
@required
- (NSString * _Nullable)identifierForNavigationEntry:(LDKNavigationController * _Nonnull)navigationViewController SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit34LDKNavigationHistoryViewController")
@interface LDKNavigationHistoryViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)tableView:(UITableView * _Nonnull)tableView canEditRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UITableViewCellEditingStyle)tableView:(UITableView * _Nonnull)tableView editingStyleForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)tableView:(UITableView * _Nonnull)tableView shouldIndentWhileEditingRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class LDKTouchView;
@class UILongPressGestureRecognizer;

SWIFT_CLASS_NAMED("LDKNavigationViewController")
@interface LDKNavigationViewController : UIViewController <LDKSearchFilterDelegate, UINavigationControllerDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LDKNavigationViewController * _Nonnull sharedInstance;)
+ (LDKNavigationViewController * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) LDKDrawerMode currentRightDrawerMode;
@property (nonatomic, strong) LDKNavigationController * _Nullable mainNavigationController;
@property (nonatomic, strong) LDKTouchView * _Nullable touchView;
@property (nonatomic, copy) NSString * _Nullable lastSearchText;
- (void)reset;
@property (nonatomic, readonly, strong) id <LDKDetailForm> _Nullable currentDetailform;
+ (LDKDrawerMode)drawerModeFromString:(NSString * _Nonnull)modeString SWIFT_WARN_UNUSED_RESULT;
+ (LDKDrawerMode)drawerModeFromObj:(id _Nullable)obj SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@property (nonatomic, readonly) BOOL shouldAutorotate;
- (void)viewDidLayoutSubviews;
- (void)update;
- (void)updateDelegateState:(UIViewController * _Nonnull)vc;
- (void)showViewController:(UIViewController * _Nonnull)vc animate:(BOOL)animate;
- (void)showPreviousViewController;
- (void)setBreadCrumbLabel:(NSString * _Nonnull)label viewController:(UIViewController * _Nonnull)viewController;
- (void)hideLeftDrawer:(BOOL)animated;
- (void)hideRightDrawer:(BOOL)animated;
- (void)hideRightDrawer:(BOOL)animated completion:(void (^ _Nullable)(BOOL))completion;
- (void)showViewControllerInLeftDrawer:(UIViewController * _Nonnull)viewController animated:(BOOL)animated mode:(LDKDrawerMode)mode;
- (void)setModeForRightDrawer:(LDKDrawerMode)mode animated:(BOOL)animated forceResize:(BOOL)forceResize;
- (void)showViewControllerInRightDrawer:(UIViewController * _Nonnull)viewController animated:(BOOL)animated mode:(LDKDrawerMode)mode;
- (void)showViewControllerInRightDrawer:(UIViewController * _Nonnull)viewController animated:(BOOL)animated mode:(LDKDrawerMode)mode touchOutside:(void (^ _Nullable)(UIView * _Nonnull))touchOutside;
- (BOOL)showViewControllerModal:(UIViewController * _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
- (BOOL)removeModalViewController SWIFT_WARN_UNUSED_RESULT;
- (void)infoButtonPressed:(UIButton * _Nonnull)sender;
- (void)backButtonPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender;
- (void)backButtonLongPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender gesture:(UILongPressGestureRecognizer * _Nonnull)gesture;
- (void)hamburgerButtonPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender appDefs:(NSArray<LDMItem *> * _Nullable)aAppDefs;
- (void)createButtonPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender;
- (void)scanButtonPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender;
- (void)exportButtonPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender;
- (void)discussionButtonPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender;
- (void)searchButtonPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender;
- (void)filterViewController:(LDKSearchFilterViewController * _Nonnull)controller didSubmitSearchText:(NSString * _Nullable)searchText searchItem:(LDMSearch * _Nullable)searchItem queryFilter:(LDMQueryFilter * _Nullable)queryFilter;
- (void)navigationController:(UINavigationController * _Nonnull)navigationController willShowViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated;
- (void)navigationController:(UINavigationController * _Nonnull)navigationController didShowViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol LDKTableOptionDelegate;

SWIFT_CLASS("_TtC17LiquidPlatformKit28LDKTableOptionViewController")
@interface LDKTableOptionViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) id <LDKTableOptionDelegate> _Nullable delegate;
@property (nonatomic, strong) LDMItem * _Null_unspecified item;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)handleOptionSelect:(NSInteger)index;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit27LDKScanOptionViewController")
@interface LDKScanOptionViewController : LDKTableOptionViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit14LDKShareButton")
@interface LDKShareButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
- (void)layoutSubviews;
@end

@class UILabel;

SWIFT_CLASS("_TtC17LiquidPlatformKit24LDKSubtitleTableViewCell")
@interface LDKSubtitleTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified subTitleLabel;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit18LDKTableOptionCell")
@interface LDKTableOptionCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit22LDKTableOptionDelegate_")
@protocol LDKTableOptionDelegate
- (void)optionSelected:(LDMItem * _Nonnull)option item:(LDMItem * _Nonnull)item;
@end



SWIFT_CLASS("_TtC17LiquidPlatformKit20LDKVerticalStackView")
@interface LDKVerticalStackView : UIView
@property (nonatomic, copy) NSArray<UIView *> * _Nonnull arrangedSubviews;
@property (nonatomic) CGFloat spacing;
- (void)reloadData;
- (void)removeAll;
- (void)removeMissing:(NSArray<UIView *> * _Nonnull)views;
- (void)addArrangedSubview:(UIView * _Nonnull)view belowView:(UIView * _Nullable)belowView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class LDMItemSchema;

SWIFT_CLASS_NAMED("LDMDataGridStyle")
@interface LDMDataGridStyle : LDMItem
@property (nonatomic, copy) NSString * _Nullable dataGridStyleId;
- (LDMItem * _Nullable)findColumnStyle:(NSString * _Nonnull)dataGridColumnStyleId SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) UIColor * _Nonnull headerBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull headerTextColor;
@property (nonatomic, readonly, strong) UIFont * _Nonnull headerTextFont;
@property (nonatomic, readonly, strong) UIColor * _Nonnull rowHighlightBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull footerBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull footerTextColor;
@property (nonatomic, readonly, strong) UIFont * _Nonnull footerTextFont;
@property (nonatomic, readonly, strong) UIColor * _Nonnull navigationButtonColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull rowBorderColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull lockedRowBorderColor;
@property (nonatomic, readonly) UIEdgeInsets gridInsets;
@property (nonatomic, readonly) UIEdgeInsets valueInsets;
- (nonnull instancetype)initWithDict:(NSDictionary * _Nullable)dict OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithItemSchema:(LDMItemSchema * _Nullable)itemSchema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithItemSchema:(LDMItemSchema * _Nonnull)anItemSchema addDynamicMethods:(BOOL)addDynamic OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(NSString * _Nonnull)itemType withDataDict:(NSDictionary * _Nullable)dataDictionary withHeaderDict:(NSDictionary * _Nullable)headerDictionary OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface LDMDataManager (SWIFT_EXTENSION(LiquidPlatformKit))
- (void)fetchGoalDetailForm:(NSString * _Nonnull)goalId completion:(void (^ _Nonnull)(LDMItem * _Nullable))completion;
@end

@class LDMSchemaField;

@interface LDMDataManager (SWIFT_EXTENSION(LiquidPlatformKit))
- (void)generateFTSForAllTypes:(SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nonnull, float))statusBlock;
- (void)generateFTSForSchema:(LDMItemSchema * _Nonnull)schema statusBlock:(SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nonnull, float))statusBlock;
- (void)generateFTSTable:(LDMItemSchema * _Nonnull)schema searchIndexName:(NSString * _Nonnull)searchIndexName searchFields:(NSArray<LDMSchemaField *> * _Nonnull)searchFields;
- (NSArray<NSString *> * _Nonnull)stringsToPrefixMatchTerms:(NSArray<NSString *> * _Nonnull)terms SWIFT_WARN_UNUSED_RESULT;
@end


@interface LDMFunction (SWIFT_EXTENSION(LiquidPlatformKit))
+ (void)allItemsFromSwaggerPath:(NSString * _Nonnull)swaggerPath completion:(void (^ _Nonnull)(LDMSearchResults * _Nullable))completion;
+ (void)allItemsFromVirtualFunctionPath:(NSString * _Nonnull)functionPath completion:(void (^ _Nonnull)(LDMSearchResults * _Nullable))completion;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit17LiveMessageParser")
@interface LiveMessageParser : NSObject
@property (nonatomic, copy) NSString * _Nullable match;
- (void)update:(NSString * _Nonnull)aText submit:(BOOL)submit;
- (void)updateMatch:(NSString * _Nonnull)replace;
- (void)clearMatch;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit13MIBadgeButton")
@interface MIBadgeButton : UIButton
@property (nonatomic, copy) NSString * _Nullable badgeString;
@property (nonatomic, strong) UIColor * _Nonnull badgeBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull badgeTextColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)initWithFrameWithFrame:(CGRect)frame withBadgeString:(NSString * _Nonnull)badgeString withBadgeInsets:(UIEdgeInsets)badgeInsets SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit33NavigationViewControllerContainer_")
@protocol NavigationViewControllerContainer
- (UIViewController * _Nullable)childViewController:(LDKNavigationViewController * _Nonnull)navigationViewController SWIFT_WARN_UNUSED_RESULT;
@end

@protocol NSObject;

@interface NSNotificationCenter (SWIFT_EXTENSION(LiquidPlatformKit))
- (id <NSObject> _Nonnull)addDiscussionObserver:(void (^ _Nonnull)(NSInteger))callback SWIFT_WARN_UNUSED_RESULT;
- (void)notifyDiscussionObserver:(void (^ _Nonnull)(NSInteger))callback updates:(NSDictionary<NSString *, NSDictionary<NSString *, LDMItem *> *> * _Nullable)updates deletes:(NSDictionary<NSString *, id> * _Nullable)deletes;
- (void)beginFiringLabeledDiscussionNotifications;
@end


SWIFT_CLASS_NAMED("SearchResultsFilteredItemModel")
@interface LDMSearchResultsFilteredItemModel : LDMSearchResults <LDKFilteredItemModelDelegate>
- (nonnull instancetype)initWithFunction:(LDMFunction * _Nonnull)function sortField:(NSString * _Nullable)sortField sortAscending:(BOOL)sortAscending OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSingleSectionStaticResults:(NSArray * _Nullable)results OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithResults:(NSArray * _Nullable)results segmentedBy:(LDMSchemaField * _Nullable)segmentKey dataManager:(LDMDataManager * _Nullable)manager OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) NSInteger numberOfSections;
@property (nonatomic, readonly) NSInteger count;
- (NSInteger)numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)titleForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)objectForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)itemForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)didInsertItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)didRemoveItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)didUpdateItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)didUpdateData:(NSArray * _Nonnull)collectedData;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

enum SearchResultsHTTPMethod : NSInteger;

SWIFT_CLASS_NAMED("SearchResultsHTTP")
@interface LDMSearchResultsHTTP : LDMSearchResults
- (nonnull instancetype)initWithUrl:(NSURL * _Nonnull)url httpMethod:(enum SearchResultsHTTPMethod)httpMethod headers:(NSDictionary<NSString *, NSString *> * _Nullable)headers postParams:(NSDictionary<NSString *, NSString *> * _Nullable)postParams OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSingleSectionStaticResults:(NSArray * _Nullable)results OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithResults:(NSArray * _Nullable)results segmentedBy:(LDMSchemaField * _Nullable)segmentKey dataManager:(LDMDataManager * _Nullable)manager OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) NSInteger numberOfSections;
@property (nonatomic, readonly) NSInteger count;
- (NSInteger)numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)titleForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)objectForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)itemForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, SearchResultsHTTPMethod) {
  SearchResultsHTTPMethodGet = 0,
  SearchResultsHTTPMethodPost = 1,
};


SWIFT_CLASS_NAMED("SequenceManager")
@interface LDKSequenceManager : NSObject
+ (void)initSequence:(NSString * _Nonnull)sequenceName SWIFT_METHOD_FAMILY(none);
+ (NSString * _Nullable)nextValueBase10String:(NSString * _Nonnull)sequenceName SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)nextValueBase36String:(NSString * _Nonnull)sequenceName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LDKTextSelectViewController;

SWIFT_CLASS_NAMED("SuggestionsViewController")
@interface LDKSuggestionsViewController : UIViewController <LDKTextSelectViewControllerDelegate>
@property (nonatomic, strong) UINavigationController * _Nonnull navController;
@property (nonatomic, copy) NSArray<LDMItem *> * _Nonnull discussionConfigs;
@property (nonatomic, copy) NSString * _Nullable discussionId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)close;
- (void)updateSuggestions:(NSString * _Nonnull)string submit:(BOOL)submit;
- (void)textSelectViewController:(LDKTextSelectViewController * _Null_unspecified)viewController didCalculateHeightNeeded:(float)heightNeeded;
- (void)textSelectViewController:(LDKTextSelectViewController * _Null_unspecified)viewController didSelectValue:(NSString * _Null_unspecified)value;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@protocol LDCSyncLogDelegate;
@class LSCSyncEventLogger;

SWIFT_CLASS_NAMED("SyncLog")
@interface LDCSyncLog : NSObject <LSCSyncEventLoggerDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LDCSyncLog * _Nonnull sharedInstance;)
+ (LDCSyncLog * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) id <LDCSyncLogDelegate> _Nullable delegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@property (nonatomic, readonly, copy) NSString * _Nonnull string;
- (void)syncEventLogger:(LSCSyncEventLogger * _Null_unspecified)logger didLogMessage:(NSString * _Null_unspecified)message;
@end


SWIFT_PROTOCOL_NAMED("SyncLogDelegate")
@protocol LDCSyncLogDelegate
- (void)syncLogWasUpdated:(LDCSyncLog * _Nonnull)syncLog;
@end

@class WebSocket;
@class NSError;

SWIFT_CLASS_NAMED("SyncSocketHandler")
@interface LSCSyncSocketHandler : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LSCSyncSocketHandler * _Nonnull sharedInstance;)
+ (LSCSyncSocketHandler * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (BOOL)verifyConnection SWIFT_WARN_UNUSED_RESULT;
- (void)websocketDidConnectWithSocket:(WebSocket * _Nonnull)socket;
- (void)websocketDidDisconnectWithSocket:(WebSocket * _Nonnull)socket error:(NSError * _Nullable)error;
- (void)websocketDidReceiveMessageWithSocket:(WebSocket * _Nonnull)socket text:(NSString * _Nonnull)text;
- (void)websocketDidReceiveDataWithSocket:(WebSocket * _Nonnull)socket data:(NSData * _Nonnull)data;
@end


@interface UIScreen (SWIFT_EXTENSION(LiquidPlatformKit))
@property (nonatomic, readonly) CGFloat screenWidth;
@property (nonatomic, readonly) CGFloat screenHeight;
@property (nonatomic, readonly) UIInterfaceOrientation screenOrientation;
- (CGFloat)screenWidthForOrientation:(UIInterfaceOrientation)orientation SWIFT_WARN_UNUSED_RESULT;
@end

@class UITapGestureRecognizer;

@interface UITextView (SWIFT_EXTENSION(LiquidPlatformKit))
- (void)removeDoubleTapRecognizer;
- (void)removeTapRecognizer;
- (UITapGestureRecognizer * _Nullable)doubleTapRecognizer SWIFT_WARN_UNUSED_RESULT;
@end

@class CAShapeLayer;

@interface UIView (SWIFT_EXTENSION(LiquidPlatformKit))
- (CAShapeLayer * _Nonnull)maskByRoundingCorners:(UIRectCorner)corners cornerRadii:(float)cornerRadii borderWidth:(float)borderWidth borderColor:(UIColor * _Nonnull)borderColor SWIFT_WARN_UNUSED_RESULT;
- (void)pinParentFull;
@end


@interface UIViewController (SWIFT_EXTENSION(LiquidPlatformKit))
- (void)safeAddChildViewController:(UIViewController * _Nonnull)viewController targetView:(UIView * _Nonnull)targetView;
- (void)safeRemoveChildViewController:(UIViewController * _Nonnull)viewController;
@end

@class NSStream;

SWIFT_CLASS("_TtC17LiquidPlatformKit9WebSocket")
@interface WebSocket : NSObject <NSStreamDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ErrorDomain;)
+ (NSString * _Nonnull)ErrorDomain SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) dispatch_queue_t _Nonnull callbackQueue;
@property (nonatomic, copy) void (^ _Nullable onConnect)(void);
@property (nonatomic, copy) void (^ _Nullable onDisconnect)(NSError * _Nullable);
@property (nonatomic, copy) void (^ _Nullable onText)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onData)(NSData * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onPong)(NSData * _Nullable);
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nonnull headers;
@property (nonatomic) BOOL voipEnabled;
@property (nonatomic) BOOL disableSSLCertValidation;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable enabledSSLCipherSuites;
@property (nonatomic, copy) NSString * _Nullable origin;
@property (nonatomic) NSInteger timeout;
@property (nonatomic, readonly) BOOL isConnected;
@property (nonatomic, readonly, copy) NSURL * _Nonnull currentURL;
/// Used for setting protocols.
- (nonnull instancetype)initWithUrl:(NSURL * _Nonnull)url protocols:(NSArray<NSString *> * _Nullable)protocols OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithUrl:(NSURL * _Nonnull)url writeQueueQOS:(NSQualityOfService)writeQueueQOS protocols:(NSArray<NSString *> * _Nullable)protocols;
/// Connect to the WebSocket server on a background thread.
- (void)connect;
/// Write a string to the websocket. This sends it as a text frame.
/// If you supply a non-nil completion block, I will perform it when the write completes.
/// \param string The string to write.
///
/// \param completion The (optional) completion handler.
///
- (void)writeWithString:(NSString * _Nonnull)string completion:(void (^ _Nullable)(void))completion;
/// Write binary data to the websocket. This sends it as a binary frame.
/// If you supply a non-nil completion block, I will perform it when the write completes.
/// \param data The data to write.
///
/// \param completion The (optional) completion handler.
///
- (void)writeWithData:(NSData * _Nonnull)data completion:(void (^ _Nullable)(void))completion;
/// Write a ping to the websocket. This sends it as a control frame.
/// Yodel a   sound  to the planet.    This sends it as an astroid. http://youtu.be/Eu5ZJELRiJ8?t=42s
- (void)writeWithPing:(NSData * _Nonnull)ping completion:(void (^ _Nullable)(void))completion;
/// Delegate for the stream methods. Processes incoming bytes
- (void)stream:(NSStream * _Nonnull)aStream handleEvent:(NSStreamEvent)eventCode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

#pragma clang diagnostic pop
