// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Dispatch;
@import UIKit;
@import CoreGraphics;
@import Foundation;
#endif

#import <LiquidPlatformKit/LiquidPlatformKit.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class LDCBatchOperator;

SWIFT_CLASS_NAMED("BatchOperatorCollection")
@interface LDCBatchOperatorCollection : NSObject
- (LDCBatchOperator * _Nonnull)addOperator:(NSString * _Nonnull)name batchCount:(int32_t)batchCount queue:(dispatch_queue_t _Nonnull)queue batchHandler:(void (^ _Nonnull)(NSArray * _Nonnull))batchHandler;
- (void)add:(NSString * _Nonnull)name object:(id _Nonnull)object;
- (void)add:(NSString * _Nonnull)name object:(id _Nonnull)object count:(int32_t)count weight:(int32_t)weight;
- (void)forEach:(void (^ _Nonnull)(NSString * _Nonnull name, LDCBatchOperator * _Nonnull batchOperator))body;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LDKBreadCrumbView;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit24BreadCrumbViewDataSource_")
@protocol BreadCrumbViewDataSource
- (NSInteger)numberOfLabels:(LDKBreadCrumbView * _Nonnull)breadcrumbView;
- (NSString * _Nonnull)labelForIndex:(LDKBreadCrumbView * _Nonnull)breadcrumbView index:(NSInteger)index;
@end

@class UIButton;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit22BreadCrumbViewDelegate_")
@protocol BreadCrumbViewDelegate
- (void)breadCrumbViewButtonPressed:(LDKBreadCrumbView * _Nonnull)breadCrumbView index:(NSInteger)index label:(NSString * _Nonnull)label button:(UIButton * _Nonnull)button;
@end

typedef SWIFT_ENUM(NSInteger, CellReplyMode) {
  CellReplyModeNone = 0,
  CellReplyModeReply = 1,
  CellReplyModeCancel = 2,
};

@class NSIndexPath;
@class UICollectionViewLayoutAttributes;
@class NSCoder;

SWIFT_CLASS("_TtC17LiquidPlatformKit29CollectionViewWaterfallLayout")
@interface CollectionViewWaterfallLayout : UICollectionViewLayout
@property (nonatomic) NSInteger columnCount;
@property (nonatomic) float minimumColumnSpacing;
@property (nonatomic) float minimumInteritemSpacing;
@property (nonatomic) float headerHeight;
@property (nonatomic) float footerHeight;
@property (nonatomic) UIEdgeInsets headerInset;
@property (nonatomic) UIEdgeInsets footerInset;
@property (nonatomic) UIEdgeInsets sectionInset;
- (void)prepareLayout;
- (CGSize)collectionViewContentSize;
- (UICollectionViewLayoutAttributes * _Nullable)layoutAttributesForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UICollectionViewLayoutAttributes * _Nullable)layoutAttributesForSupplementaryViewOfKind:(NSString * _Nonnull)elementKind atIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSArray<UICollectionViewLayoutAttributes *> * _Nullable)layoutAttributesForElementsInRect:(CGRect)rect;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)newBounds;
- (void)invalidateLayout;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit37CollectionViewWaterfallLayoutDelegate_")
@protocol CollectionViewWaterfallLayoutDelegate <UICollectionViewDelegate>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)layout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@optional
- (float)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)layout heightForHeaderInSection:(NSInteger)section;
- (float)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)layout heightForFooterInSection:(NSInteger)section;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)layout insetForSection:(NSInteger)section;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)layout insetForHeaderInSection:(NSInteger)section;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)layout insetForFooterInSection:(NSInteger)section;
- (float)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)layout minimumInteritemSpacingForSection:(NSInteger)section;
@end

@class NSBundle;

SWIFT_CLASS("_TtC17LiquidPlatformKit24DetailFormViewController")
@interface DetailFormViewController : UIViewController
@property (nonatomic, strong) UIViewController * _Nullable contentViewController;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)reloadData;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class LDMItem;

SWIFT_CLASS_NAMED("ExecuteInsightDecisions")
@interface ExecuteInsightDecisions : NSObject
+ (void)setFieldsFromOptions:(LDMItem * _Nullable)targetItem itemWithOptions:(LDMItem * _Nullable)itemWithOptions optionsFieldName:(NSString * _Nonnull)optionsFieldName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol LDKFilteredItemModelDelegate;

SWIFT_CLASS_NAMED("FilteredItemModel")
@interface LDKFilteredItemModel : NSObject
@property (nonatomic) BOOL enabled;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull updateFields;
@property (nonatomic, weak) id <LDKFilteredItemModelDelegate> _Nullable delegate;
- (void)fetchData;
- (void)destroy;
- (LDMItem * _Nonnull)itemAtIndex:(NSInteger)index;
@property (nonatomic, readonly, copy) NSArray * _Nonnull array;
- (NSInteger)count;
@end

@class LDKHamburgerMenuViewController;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit24LDCHamburgerMenuDelegate_")
@protocol LDCHamburgerMenuDelegate
- (NSArray<LDMItem *> * _Nonnull)avalibleFunctionMaps:(LDKHamburgerMenuViewController * _Nonnull)menuViewController;
- (LDMItem * _Nullable)currentFunctionMap:(LDKHamburgerMenuViewController * _Nonnull)menuViewController;
- (void)selectFunctionMap:(LDKHamburgerMenuViewController * _Nonnull)menuViewController functionMap:(LDMItem * _Nonnull)functionMap;
- (NSArray<NSString *> * _Nullable)supportedPerspectives;
- (void)changePerspective:(NSString * _Nonnull)perspective;
@end

@class LDKNavigationViewController;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit27LDCNavigationCreateDelegate_")
@protocol LDCNavigationCreateDelegate
- (BOOL)createSupported;
- (void)createButtonPressed:(LDKNavigationViewController * _Nonnull)navigationViewController sender:(UIButton * _Nonnull)sender;
@end

@protocol LDKDetailForm;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit31LDCNavigationDetailFormDelegate_")
@protocol LDCNavigationDetailFormDelegate
- (id <LDKDetailForm> _Nullable)currentDetailForm;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit26LDCNavigationEventDelegate_")
@protocol LDCNavigationEventDelegate
@optional
- (void)backEvent;
- (void)willOpenRightDrawer:(UIViewController * _Nonnull)viewController animated:(BOOL)animated mode:(LDKDrawerMode)mode width:(CGFloat)width;
- (void)didOpenRightDrawer:(UIViewController * _Nonnull)viewController animated:(BOOL)animated mode:(LDKDrawerMode)mode width:(CGFloat)width;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit27LDCNavigationExportDelegate_")
@protocol LDCNavigationExportDelegate
- (BOOL)exportSupported;
- (void)exportButtonPressed:(LDKNavigationViewController * _Nonnull)navigationViewController sender:(UIButton * _Nonnull)sender;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit25LDCNavigationScanDelegate_")
@protocol LDCNavigationScanDelegate
- (BOOL)scanSupported;
- (void)scanButtonPressed:(LDKNavigationViewController * _Nonnull)navigationViewController sender:(UIButton * _Nonnull)sender;
@end

@class LDKSearchFilterViewController;
@class LDMSearch;
@class LDMQueryFilter;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit27LDCNavigationSearchDelegate_")
@protocol LDCNavigationSearchDelegate
- (NSDictionary<NSString *, id> * _Nullable)searchSupportedForConfig;
- (void)didSubmitSearch:(LDKNavigationViewController * _Nonnull)navigationViewController filterViewController:(LDKSearchFilterViewController * _Nonnull)filterViewController searchText:(NSString * _Nullable)searchText searchItem:(LDMSearch * _Nullable)searchItem queryFilter:(LDMQueryFilter * _Nullable)queryFilter;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit33LDCOffice365ConnectViewController")
@interface LDCOffice365ConnectViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIFont;
@class UIView;

SWIFT_CLASS("_TtC17LiquidPlatformKit25LDKAccordionSectionConfig")
@interface LDKAccordionSectionConfig : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) UIFont * _Nullable font;
@property (nonatomic, strong) UIView * _Nullable view;
@property (nonatomic) BOOL expanded;
@property (nonatomic) LDKAccordionSectionType type;
@property (nonatomic, strong) id _Nullable config;
@property (nonatomic, copy) NSString * _Nullable modeVisibility;
@property (nonatomic, copy) NSArray * _Nullable visibilityRules;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end

@protocol LDKAccordionViewDataSource;
@protocol LDKAccordionViewDelegate;

SWIFT_CLASS("_TtC17LiquidPlatformKit16LDKAccordionView")
@interface LDKAccordionView : UIScrollView
@property (nonatomic, strong) id <LDKAccordionViewDataSource> _Nullable accordionDataSource;
@property (nonatomic, strong) id <LDKAccordionViewDelegate> _Nullable accordionDelegate;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)reloadData;
- (void)layoutSubviews;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit26LDKAccordionViewDataSource_")
@protocol LDKAccordionViewDataSource
- (NSInteger)numberOfSections;
- (LDKAccordionSectionConfig * _Nonnull)configForSection:(NSInteger)_;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit24LDKAccordionViewDelegate_")
@protocol LDKAccordionViewDelegate
- (void)didPressTitle:(NSInteger)idx;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit17LDKBreadCrumbView")
@interface LDKBreadCrumbView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
- (void)reloadData;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit15LDKCameraButton")
@interface LDKCameraButton : UIButton
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit15LDKCreateButton")
@interface LDKCreateButton : UIButton
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
- (void)layoutSubviews;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit13LDKDetailForm_")
@protocol LDKDetailForm
- (LDMItem * _Nullable)currentFunctionItem;
@end

@class NSLayoutManager;
@class UITextView;
@class NSTextAttachment;
@class NSURL;

SWIFT_CLASS("_TtC17LiquidPlatformKit33LDKDiscussionMessageTableViewCell")
@interface LDKDiscussionMessageTableViewCell : UITableViewCell <NSLayoutManagerDelegate, UITextViewDelegate>
@property (nonatomic) enum CellReplyMode replyMode;
@property (nonatomic) BOOL isSubMessage;
+ (CGFloat)cellHeightToFitMessage:(LDMItem * _Nonnull)message expanded:(BOOL)expanded showingDate:(BOOL)showingDate;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (void)setDiscussion:(LDMItem * _Nonnull)discussion expanded:(BOOL)expanded showingDate:(BOOL)showingDate;
- (void)update;
- (NSString * _Nonnull)initialsForUser:(LDMItem * _Nonnull)user;
- (NSString * _Nonnull)initialForUser:(LDMItem * _Nonnull)user field:(NSString * _Nonnull)field;
- (CGFloat)layoutManager:(NSLayoutManager * _Nonnull)layoutManager lineSpacingAfterGlyphAtIndex:(NSInteger)glyphIndex withProposedLineFragmentRect:(CGRect)rect;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldInteractWithTextAttachment:(NSTextAttachment * _Nonnull)textAttachment inRange:(NSRange)characterRange;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldInteractWithURL:(NSURL * _Nonnull)URL inRange:(NSRange)characterRange;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit28LDKFilteredItemModelDelegate_")
@protocol LDKFilteredItemModelDelegate
- (void)didInsertItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)didRemoveItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)didUpdateItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
@optional
- (void)shouldScrollToIndex:(NSInteger)index;
@required
- (void)didUpdateData:(NSArray * _Nonnull)collectedData;
@end

@class NSMutableDictionary;
@class LDMSearchResults;
@class NSDictionary;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit20LDKInsightPopContent_")
@protocol LDKInsightPopContent
@property (nonatomic, strong) NSMutableDictionary * _Nullable options;
@property (nonatomic, readonly, strong) LDMItem * _Nullable selectedItem;
- (NSString * _Nullable)uniqueIdentifierForReportViewController:(id _Nonnull)viewController;
- (void)reloadData;
- (void)reportViewController:(UIViewController * _Nonnull)parentViewController didUpdateSearchResults:(LDMSearchResults * _Nullable)didUpdateSearchResults;
@optional
- (void)reportViewController:(UIViewController * _Nonnull)parentViewController willUpdateSearchResults:(void (^ _Nonnull)(LDMQueryFilter * _Nullable queryFilter))willUpdateSearchResults;
- (void)reportViewController:(UIViewController * _Nonnull)parentViewController didUpdateSummaryResults:(NSDictionary * _Nullable)didUpdateSummaryResults;
- (void)reportViewController:(UIViewController * _Nonnull)parentViewController selectRowAtIndexPath:(NSIndexPath * _Nonnull)selectRowAtIndexPath;
- (void)reportViewControllerDidAddChild:(UIViewController * _Nonnull)parentViewController;
@end

@class UITableView;
@class UITableViewRowAction;
@class PHFComposeBarView;

SWIFT_CLASS_NAMED("LDKDiscussionViewController")
@interface LDKDiscussionViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, PHFComposeBarViewDelegate, LDKInsightPopContent, LDCNavigationEventDelegate, LDKFilteredItemModelDelegate>
@property (nonatomic, strong) LDMItem * _Nullable selectedItem;
@property (nonatomic, strong) NSMutableDictionary * _Nullable options;
- (nonnull instancetype)initWithItem:(LDMItem * _Nonnull)item OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)didInsertItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)didRemoveItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)didUpdateItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)shouldScrollToIndex:(NSInteger)index;
- (void)didUpdateData:(NSArray * _Nonnull)collectedData;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)tableView:(UITableView * _Nonnull)tableView canEditRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSArray<UITableViewRowAction *> * _Nullable)tableView:(UITableView * _Nonnull)tableView editActionsForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)tableView:(UITableView * _Nonnull)tableView shouldShowMenuForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)tableView:(UITableView * _Nonnull)tableView canPerformAction:(SEL _Null_unspecified)action forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Nullable)sender;
- (void)tableView:(UITableView * _Nonnull)tableView performAction:(SEL _Null_unspecified)action forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Nullable)sender;
- (void)composeBarViewDidPressButton:(PHFComposeBarView * _Null_unspecified)composeBarView;
- (void)composeBarViewDidPressUtilityButton:(PHFComposeBarView * _Null_unspecified)composeBarView;
- (void)composeBarView:(PHFComposeBarView * _Null_unspecified)composeBarView willChangeFromFrame:(CGRect)startFrame toFrame:(CGRect)endFrame duration:(NSTimeInterval)duration animationCurve:(UIViewAnimationCurve)animationCurve;
- (void)didChangeText:(NSString * _Null_unspecified)text;
- (void)replyButtonPressed:(LDKDiscussionMessageTableViewCell * _Nonnull)cell discussion:(LDMItem * _Nullable)discussion sender:(UIButton * _Nonnull)sender replyMode:(enum CellReplyMode)replyMode;
- (void)textViewWasTapped:(LDKDiscussionMessageTableViewCell * _Nonnull)cell discussion:(LDMItem * _Nullable)discussion;
- (void)reportViewControllerDidAddChild:(UIViewController * _Nonnull)parentViewController;
- (NSString * _Nullable)uniqueIdentifierForReportViewController:(id _Nonnull)viewController;
- (void)reloadData;
- (void)reportViewController:(UIViewController * _Nonnull)parentViewController didUpdateSearchResults:(LDMSearchResults * _Nullable)didUpdateSearchResults;
- (void)willOpenRightDrawer:(UIViewController * _Nonnull)viewController animated:(BOOL)animated mode:(LDKDrawerMode)mode width:(CGFloat)width;
@end

@class LDKFieldValueColumnView;
@class LDKFieldValueConfig;

SWIFT_PROTOCOL("_TtP17LiquidPlatformKit29LDKFieldValueColumnDataSource_")
@protocol LDKFieldValueColumnDataSource
- (NSInteger)numberOfColumns:(LDKFieldValueColumnView * _Nonnull)fieldValueView;
- (NSInteger)numberOfFields:(LDKFieldValueColumnView * _Nonnull)fieldValueView;
- (LDKFieldValueConfig * _Nonnull)configForField:(LDKFieldValueColumnView * _Nonnull)fieldValueView index:(NSInteger)index;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit27LDKFieldValueColumnDelegate_")
@protocol LDKFieldValueColumnDelegate
- (void)didChangeValue:(LDKFieldValueColumnView * _Nonnull)fieldValueView value:(id _Nullable)value index:(NSInteger)index;
- (void)performEdit:(LDKFieldValueColumnView * _Nonnull)fieldValueView sender:(UIButton * _Nonnull)sender index:(NSInteger)index;
@optional
- (void)didChangeFirstResponder:(LDKFieldValueColumnView * _Nonnull)fieldValueView firstResponder:(UIView * _Nullable)firstResponder;
@end

@class UIColor;
@class UITextField;

SWIFT_CLASS("_TtC17LiquidPlatformKit23LDKFieldValueColumnView")
@interface LDKFieldValueColumnView : UIView <UITextFieldDelegate>
@property (nonatomic, strong) UIColor * _Null_unspecified fieldLabelColor;
@property (nonatomic, strong) UIFont * _Null_unspecified fieldLabelFont;
@property (nonatomic, strong) UIColor * _Null_unspecified fieldLabelEditableColor;
@property (nonatomic, strong) UIFont * _Null_unspecified fieldLabelEditableFont;
@property (nonatomic, strong) UIColor * _Null_unspecified valueLabelColor;
@property (nonatomic, strong) UIFont * _Null_unspecified valueLabelFont;
@property (nonatomic, strong) UIColor * _Null_unspecified valueLabelEditableColor;
@property (nonatomic, strong) UIFont * _Null_unspecified valueLabelEditableFont;
@property (nonatomic) UIEdgeInsets fieldLabelInsets;
@property (nonatomic) UIEdgeInsets valueInsets;
@property (nonatomic) UIEdgeInsets fieldValueInsets;
@property (nonatomic) UIEdgeInsets edgeInsets;
@property (nonatomic, strong) id <LDKFieldValueColumnDataSource> _Nullable datasource;
@property (nonatomic, strong) id <LDKFieldValueColumnDelegate> _Nullable delegate;
@property (nonatomic) BOOL editing;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)reloadData;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string;
@end


@class UIBarButtonItem;
@class LDKEditDetailCollectionViewCell;

SWIFT_CLASS("_TtC17LiquidPlatformKit21LDKFormViewController")
@interface LDKFormViewController : UIViewController <LDKAccordionViewDataSource, LDKAccordionViewDelegate>
@property (nonatomic, strong) LDMItem * _Nullable form;
@property (nonatomic, strong) LDMItem * _Nullable originalItem;
@property (nonatomic) BOOL deleteButtonEnabled;
@property (nonatomic) BOOL transact;
@property (nonatomic) BOOL autoDismiss;
@property (nonatomic) BOOL autoEdit;
@property (nonatomic) BOOL executeCreateOptions;
@property (nonatomic, copy) NSString * _Nonnull transactionId;
@property (nonatomic, copy) NSDictionary<NSNumber *, NSNumber *> * _Nonnull heightNeededByIndex;
@property (nonatomic, copy) NSDictionary<NSNumber *, NSNumber *> * _Nonnull wasLoadedByIndex;
@property (nonatomic, copy) void (^ _Nullable didSave)(UIBarButtonItem * _Nonnull sender, LDMItem * _Nonnull aItem);
@property (nonatomic, copy) void (^ _Nullable didCancel)(UIBarButtonItem * _Nonnull sender, LDMItem * _Nonnull aItem);
@property (nonatomic, copy) void (^ _Nullable didDelete)(UIBarButtonItem * _Nonnull sender, LDMItem * _Nonnull aItem);
@property (nonatomic, copy) void (^ _Nullable didPressMenu)(UIButton * _Nonnull sender, LDMItem * _Nonnull aItem);
@property (nonatomic, copy) void (^ _Nullable shouldClose)(UIButton * _Nonnull sender, LDMItem * _Nonnull aItem);
@property (nonatomic) LDKDrawerMode drawerMode;
@property (nonatomic) BOOL performLocalQueries;
@property (nonatomic, copy) NSString * _Nullable functionType;
@property (nonatomic, readonly) BOOL hasUnsavedChanges;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
@property (nonatomic, strong) LDMItem * _Nullable item;
@property (nonatomic) BOOL disableEdit;
- (void)reloadData:(BOOL)animate;
- (void)refresh;
- (void)reloadRow:(NSInteger)aIndex;
- (void)loadConfiguration:(LDMItem * _Nonnull)aForm;
- (void)setAllExpanded:(BOOL)expanded;
- (void)setEditing:(BOOL)editing animated:(BOOL)animated;
- (NSInteger)numberOfSections;
- (LDKAccordionSectionConfig * _Nonnull)configForSection:(NSInteger)idx;
- (void)didPressTitle:(NSInteger)idx;
- (void)collectionViewCell:(LDKEditDetailCollectionViewCell * _Nonnull)cell didModifyItem:(LDMItem * _Nonnull)item fields:(NSArray * _Nonnull)fields;
- (void)collectionViewCell:(LDKEditDetailCollectionViewCell * _Nonnull)cell didChangeFirstResponder:(UIView * _Nullable)firstResponder;
- (void)collectionViewCell:(LDKEditDetailCollectionViewCell * _Null_unspecified)cell didChangeSizeNeeded:(CGSize)sizeNeeded scroll:(BOOL)scroll;
@end


SWIFT_CLASS_NAMED("LDKHamburgerMenuViewController")
@interface LDKHamburgerMenuViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
+ (NSString * _Nonnull)cardPerspective;
+ (NSString * _Nonnull)gridPerspective;
+ (NSString * _Nonnull)mapPerspective;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)updateDelegateState;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@class UINavigationController;

SWIFT_CLASS("_TtC17LiquidPlatformKit24LDKMenuBarViewController")
@interface LDKMenuBarViewController : UIViewController <UINavigationControllerDelegate, BreadCrumbViewDelegate, BreadCrumbViewDataSource>
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)setDiscussionsBadgeText:(NSString * _Nullable)text;
- (void)setCreatable:(BOOL)creatable;
- (void)setSearchable:(BOOL)searchable;
- (void)setScanable:(BOOL)scanable;
- (void)setExportable:(BOOL)exportable;
- (void)setDiscussable:(BOOL)discussable;
- (void)reloadData;
- (void)navigationController:(UINavigationController * _Nonnull)navigationController willShowViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated;
- (void)breadCrumbViewButtonPressed:(LDKBreadCrumbView * _Nonnull)breadCrumbView index:(NSInteger)index label:(NSString * _Nonnull)label button:(UIButton * _Nonnull)button;
- (NSInteger)numberOfLabels:(LDKBreadCrumbView * _Nonnull)breadcrumbView;
- (NSString * _Nonnull)labelForIndex:(LDKBreadCrumbView * _Nonnull)breadcrumbView index:(NSInteger)index;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit29LDKModalWrapperViewController")
@interface LDKModalWrapperViewController : UIViewController
@property (nonatomic, strong) UIViewController * _Nullable contentViewController;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit23LDKNavigationController")
@interface LDKNavigationController : UINavigationController
@property (nonatomic, copy) NSArray<UIViewController *> * _Nonnull viewControllerHistory;
@property (nonatomic, readonly, strong) UIViewController * _Nullable topViewController;
@property (nonatomic, copy) NSArray<UIViewController *> * _Nonnull viewControllers;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)didReceiveMemoryWarning;
- (UIInterfaceOrientationMask)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (UIViewController * _Nullable)popViewControllerAnimated:(BOOL)animated;
- (NSArray<UIViewController *> * _Nullable)popToViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated;
- (NSArray<UIViewController *> * _Nullable)popToRootViewControllerAnimated:(BOOL)animated;
- (void)pushViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated;
- (void)setBreadCrumbLabel:(NSString * _Nonnull)label viewController:(UIViewController * _Nonnull)viewController;
- (void)removeBreadCrumbLabel:(UIViewController * _Nonnull)viewController;
- (NSString * _Nullable)breadCrumbLabelForIndex:(NSInteger)index;
- (NSString * _Nullable)breadCrumbLabelForViewController:(UIViewController * _Nonnull)viewController;
- (UIViewController * _Nullable)viewControllerForBreadCrumbLabel:(NSString * _Nonnull)breadCrumbLabel;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull identifiers;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit18LDKNavigationEntry_")
@protocol LDKNavigationEntry
@optional
- (BOOL)historyEntryUnique;
@required
- (NSString * _Nullable)identifierForNavigationEntry:(LDKNavigationController * _Nonnull)navigationViewController;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit34LDKNavigationHistoryViewController")
@interface LDKNavigationHistoryViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)tableView:(UITableView * _Nonnull)tableView canEditRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UITableViewCellEditingStyle)tableView:(UITableView * _Nonnull)tableView editingStyleForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)tableView:(UITableView * _Nonnull)tableView shouldIndentWhileEditingRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class LDKTouchView;
@class UILongPressGestureRecognizer;

SWIFT_CLASS_NAMED("LDKNavigationViewController")
@interface LDKNavigationViewController : UIViewController <LDKSearchFilterDelegate, UINavigationControllerDelegate>
+ (LDKNavigationViewController * _Nonnull)sharedInstance;
@property (nonatomic) LDKDrawerMode currentRightDrawerMode;
@property (nonatomic, strong) LDKNavigationController * _Nullable mainNavigationController;
@property (nonatomic, strong) LDKTouchView * _Nullable touchView;
@property (nonatomic, copy) NSString * _Nullable lastSearchText;
- (void)reset;
@property (nonatomic, readonly, strong) id <LDKDetailForm> _Nullable currentDetailform;
+ (LDKDrawerMode)drawerModeFromString:(NSString * _Nonnull)modeString;
+ (LDKDrawerMode)drawerModeFromObj:(id _Nullable)obj;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (UIStatusBarStyle)preferredStatusBarStyle;
- (UIInterfaceOrientationMask)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)viewDidLayoutSubviews;
- (void)update;
- (void)updateDelegateState:(UIViewController * _Nonnull)vc;
- (void)showViewController:(UIViewController * _Nonnull)vc animate:(BOOL)animate;
- (void)showPreviousViewController;
- (void)setBreadCrumbLabel:(NSString * _Nonnull)label viewController:(UIViewController * _Nonnull)viewController;
- (void)hideLeftDrawer:(BOOL)animated;
- (void)hideRightDrawer:(BOOL)animated;
- (void)hideRightDrawer:(BOOL)animated completion:(void (^ _Nullable)(BOOL success))completion;
- (void)showViewControllerInLeftDrawer:(UIViewController * _Nonnull)viewController animated:(BOOL)animated mode:(LDKDrawerMode)mode;
- (void)setModeForRightDrawer:(LDKDrawerMode)mode animated:(BOOL)animated forceResize:(BOOL)forceResize;
- (void)showViewControllerInRightDrawer:(UIViewController * _Nonnull)viewController animated:(BOOL)animated mode:(LDKDrawerMode)mode;
- (void)showViewControllerInRightDrawer:(UIViewController * _Nonnull)viewController animated:(BOOL)animated mode:(LDKDrawerMode)mode touchOutside:(void (^ _Nullable)(UIView * _Nonnull sender))touchOutside;
- (BOOL)showViewControllerModal:(UIViewController * _Nonnull)viewController;
- (BOOL)removeModalViewController;
- (void)infoButtonPressed:(UIButton * _Nonnull)sender;
- (void)backButtonPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender;
- (void)backButtonLongPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender gesture:(UILongPressGestureRecognizer * _Nonnull)gesture;
- (void)hamburgerButtonPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender appDefs:(NSArray<LDMItem *> * _Nullable)aAppDefs;
- (void)createButtonPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender;
- (void)scanButtonPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender;
- (void)exportButtonPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender;
- (void)discussionButtonPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender;
- (void)searchButtonPressed:(LDKMenuBarViewController * _Nonnull)menuBarViewController sender:(UIButton * _Nonnull)sender;
- (void)filterViewController:(LDKSearchFilterViewController * _Nonnull)controller didSubmitSearchText:(NSString * _Nullable)searchText searchItem:(LDMSearch * _Nullable)searchItem queryFilter:(LDMQueryFilter * _Nullable)queryFilter;
- (void)navigationController:(UINavigationController * _Nonnull)navigationController willShowViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated;
- (void)navigationController:(UINavigationController * _Nonnull)navigationController didShowViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol LDKTableOptionDelegate;

SWIFT_CLASS("_TtC17LiquidPlatformKit28LDKTableOptionViewController")
@interface LDKTableOptionViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) id <LDKTableOptionDelegate> _Nullable delegate;
@property (nonatomic, strong) LDMItem * _Null_unspecified item;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)handleOptionSelect:(NSInteger)index;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit27LDKScanOptionViewController")
@interface LDKScanOptionViewController : LDKTableOptionViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit14LDKShareButton")
@interface LDKShareButton : UIButton
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
- (void)layoutSubviews;
@end

@class UILabel;

SWIFT_CLASS("_TtC17LiquidPlatformKit24LDKSubtitleTableViewCell")
@interface LDKSubtitleTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified subTitleLabel;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit18LDKTableOptionCell")
@interface LDKTableOptionCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit22LDKTableOptionDelegate_")
@protocol LDKTableOptionDelegate
- (void)optionSelected:(LDMItem * _Nonnull)option item:(LDMItem * _Nonnull)item;
@end



SWIFT_CLASS("_TtC17LiquidPlatformKit20LDKVerticalStackView")
@interface LDKVerticalStackView : UIView
@property (nonatomic, copy) NSArray<UIView *> * _Nonnull arrangedSubviews;
@property (nonatomic) CGFloat spacing;
- (void)reloadData;
- (void)removeAll;
- (void)removeMissing:(NSArray<UIView *> * _Nonnull)views;
- (void)addArrangedSubview:(UIView * _Nonnull)view belowView:(UIView * _Nullable)belowView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class LDMItemSchema;

SWIFT_CLASS_NAMED("LDMDataGridStyle")
@interface LDMDataGridStyle : LDMItem
@property (nonatomic, copy) NSString * _Nullable dataGridStyleId;
- (LDMItem * _Nullable)findColumnStyle:(NSString * _Nonnull)dataGridColumnStyleId;
@property (nonatomic, readonly, strong) UIColor * _Nonnull headerBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull headerTextColor;
@property (nonatomic, readonly, strong) UIFont * _Nonnull headerTextFont;
@property (nonatomic, readonly, strong) UIColor * _Nonnull rowHighlightBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull footerBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull footerTextColor;
@property (nonatomic, readonly, strong) UIFont * _Nonnull footerTextFont;
@property (nonatomic, readonly, strong) UIColor * _Nonnull navigationButtonColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull rowBorderColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull lockedRowBorderColor;
@property (nonatomic, readonly) UIEdgeInsets gridInsets;
@property (nonatomic, readonly) UIEdgeInsets valueInsets;
- (nonnull instancetype)initWithDict:(NSDictionary * _Nullable)dict OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithItemSchema:(LDMItemSchema * _Nonnull)itemSchema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithItemSchema:(LDMItemSchema * _Nonnull)anItemSchema addDynamicMethods:(BOOL)addDynamic OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(NSString * _Nonnull)itemType withDataDict:(NSDictionary * _Nullable)dataDictionary withHeaderDict:(NSDictionary * _Nullable)headerDictionary OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface LDMDataManager (SWIFT_EXTENSION(LiquidPlatformKit))
- (void)fetchGoalDetailForm:(NSString * _Nonnull)goalId completion:(void (^ _Nonnull)(LDMItem * _Nullable detailForm))completion;
@end

@class LDMSchemaField;

@interface LDMDataManager (SWIFT_EXTENSION(LiquidPlatformKit))
- (void)generateFTSForAllTypes:(void (^ _Nonnull)(NSString * _Nonnull statusMessage, float percentComplete))statusBlock;
- (void)generateFTSForSchema:(LDMItemSchema * _Nonnull)schema statusBlock:(void (^ _Nonnull)(NSString * _Nonnull statusMessage, float percentComplete))statusBlock;
- (void)generateFTSTable:(LDMItemSchema * _Nonnull)schema searchIndexName:(NSString * _Nonnull)searchIndexName searchFields:(NSArray<LDMSchemaField *> * _Nonnull)searchFields;
- (NSArray<NSString *> * _Nonnull)stringsToPrefixMatchTerms:(NSArray<NSString *> * _Nonnull)terms;
@end


@interface LDMFunction (SWIFT_EXTENSION(LiquidPlatformKit))
+ (void)allItemsFromSwaggerPath:(NSString * _Nonnull)swaggerPath completion:(void (^ _Nonnull)(LDMSearchResults * _Nullable))completion;
+ (void)allItemsFromVirtualFunctionPath:(NSString * _Nonnull)functionPath completion:(void (^ _Nonnull)(LDMSearchResults * _Nullable))completion;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit17LiveMessageParser")
@interface LiveMessageParser : NSObject
@property (nonatomic, copy) NSString * _Nullable match;
- (void)update:(NSString * _Nonnull)aText submit:(BOOL)submit;
- (void)updateMatch:(NSString * _Nonnull)replace;
- (void)clearMatch;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LiquidPlatformKit13MIBadgeButton")
@interface MIBadgeButton : UIButton
@property (nonatomic, copy) NSString * _Nullable badgeString;
@property (nonatomic, strong) UIColor * _Nonnull badgeBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull badgeTextColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)initWithFrameWithFrame:(CGRect)frame withBadgeString:(NSString * _Nonnull)badgeString withBadgeInsets:(UIEdgeInsets)badgeInsets;
@end


@interface NSCharacterSet (SWIFT_EXTENSION(LiquidPlatformKit))
@end

@protocol NSObject;

@interface NSNotificationCenter (SWIFT_EXTENSION(LiquidPlatformKit))
- (id <NSObject> _Nonnull)addDiscussionObserver:(void (^ _Nonnull)(NSInteger unreadDiscussionCount))callback;
- (void)notifyDiscussionObserver:(void (^ _Nonnull)(NSInteger unreadDiscussionCount))callback updates:(NSDictionary<NSString *, NSDictionary<NSString *, LDMItem *> *> * _Nullable)updates deletes:(NSDictionary<NSString *, id> * _Nullable)deletes;
- (void)beginFiringLabeledDiscussionNotifications;
@end


SWIFT_PROTOCOL("_TtP17LiquidPlatformKit33NavigationViewControllerContainer_")
@protocol NavigationViewControllerContainer
- (UIViewController * _Nullable)childViewController:(LDKNavigationViewController * _Nonnull)navigationViewController;
@end


SWIFT_CLASS_NAMED("SearchResultsFilteredItemModel")
@interface LDMSearchResultsFilteredItemModel : LDMSearchResults <LDKFilteredItemModelDelegate>
- (nonnull instancetype)initWithFunction:(LDMFunction * _Nonnull)function sortField:(NSString * _Nullable)sortField sortAscending:(BOOL)sortAscending OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSingleSectionStaticResults:(NSArray * _Nullable)results OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithResults:(NSArray * _Nullable)results segmentedBy:(LDMSchemaField * _Nullable)segmentKey dataManager:(LDMDataManager * _Nullable)manager OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) NSInteger numberOfSections;
@property (nonatomic, readonly) NSInteger count;
- (NSInteger)numberOfRowsInSection:(NSInteger)section;
- (NSString * _Nullable)titleForHeaderInSection:(NSInteger)section;
- (id _Nullable)objectForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (id _Nullable)itemForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)didInsertItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)didRemoveItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)didUpdateItem:(LDMItem * _Nonnull)item index:(NSInteger)index;
- (void)didUpdateData:(NSArray * _Nonnull)collectedData;
@end

enum SearchResultsHTTPMethod : NSInteger;

SWIFT_CLASS_NAMED("SearchResultsHTTP")
@interface LDMSearchResultsHTTP : LDMSearchResults
- (nonnull instancetype)initWithUrl:(NSURL * _Nonnull)url httpMethod:(enum SearchResultsHTTPMethod)httpMethod headers:(NSDictionary<NSString *, NSString *> * _Nullable)headers postParams:(NSDictionary<NSString *, NSString *> * _Nullable)postParams OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSingleSectionStaticResults:(NSArray * _Nullable)results OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithResults:(NSArray * _Nullable)results segmentedBy:(LDMSchemaField * _Nullable)segmentKey dataManager:(LDMDataManager * _Nullable)manager OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) NSInteger numberOfSections;
@property (nonatomic, readonly) NSInteger count;
- (NSInteger)numberOfRowsInSection:(NSInteger)section;
- (NSString * _Nullable)titleForHeaderInSection:(NSInteger)section;
- (id _Nullable)objectForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (id _Nullable)itemForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

typedef SWIFT_ENUM(NSInteger, SearchResultsHTTPMethod) {
  SearchResultsHTTPMethodGET = 0,
  SearchResultsHTTPMethodPOST = 1,
};


SWIFT_CLASS_NAMED("SequenceManager")
@interface LDKSequenceManager : NSObject
+ (void)initSequence:(NSString * _Nonnull)sequenceName;
+ (NSString * _Nullable)nextValueBase10String:(NSString * _Nonnull)sequenceName;
+ (NSString * _Nonnull)nextValueBase36String:(NSString * _Nonnull)sequenceName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LDKTextSelectViewController;

SWIFT_CLASS_NAMED("SuggestionsViewController")
@interface LDKSuggestionsViewController : UIViewController <LDKTextSelectViewControllerDelegate>
@property (nonatomic, strong) UINavigationController * _Nonnull navController;
@property (nonatomic, copy) NSArray<LDMItem *> * _Nonnull discussionConfigs;
@property (nonatomic, copy) NSString * _Nullable discussionId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)close;
- (void)updateSuggestions:(NSString * _Nonnull)string submit:(BOOL)submit;
- (void)textSelectViewController:(LDKTextSelectViewController * _Null_unspecified)viewController didCalculateHeightNeeded:(float)heightNeeded;
- (void)textSelectViewController:(LDKTextSelectViewController * _Null_unspecified)viewController didSelectValue:(NSString * _Null_unspecified)value;
@end

@protocol LDCSyncLogDelegate;
@class LSCSyncEventLogger;

SWIFT_CLASS_NAMED("SyncLog")
@interface LDCSyncLog : NSObject <LSCSyncEventLoggerDelegate>
+ (LDCSyncLog * _Nonnull)sharedInstance;
@property (nonatomic, strong) id <LDCSyncLogDelegate> _Nullable delegate;
@property (nonatomic, readonly, copy) NSString * _Nonnull string;
- (void)syncEventLogger:(LSCSyncEventLogger * _Null_unspecified)logger didLogMessage:(NSString * _Null_unspecified)message;
@end


SWIFT_PROTOCOL_NAMED("SyncLogDelegate")
@protocol LDCSyncLogDelegate
- (void)syncLogWasUpdated:(LDCSyncLog * _Nonnull)syncLog;
@end

@class WebSocket;
@class NSError;
@class NSData;

SWIFT_CLASS_NAMED("SyncSocketHandler")
@interface LSCSyncSocketHandler : NSObject
+ (LSCSyncSocketHandler * _Nonnull)sharedInstance;
- (BOOL)verifyConnection;
- (void)websocketDidConnect:(WebSocket * _Nonnull)socket;
- (void)websocketDidDisconnect:(WebSocket * _Nonnull)socket error:(NSError * _Nullable)error;
- (void)websocketDidReceiveMessage:(WebSocket * _Nonnull)socket text:(NSString * _Nonnull)text;
- (void)websocketDidReceiveData:(WebSocket * _Nonnull)socket data:(NSData * _Nonnull)data;
@end


@interface UIScreen (SWIFT_EXTENSION(LiquidPlatformKit))
@property (nonatomic, readonly) CGFloat screenWidth;
@property (nonatomic, readonly) CGFloat screenHeight;
@property (nonatomic, readonly) UIInterfaceOrientation screenOrientation;
- (CGFloat)screenWidthForOrientation:(UIInterfaceOrientation)orientation;
@end

@class UITapGestureRecognizer;

@interface UITextView (SWIFT_EXTENSION(LiquidPlatformKit))
- (void)removeDoubleTapRecognizer;
- (void)removeTapRecognizer;
- (UITapGestureRecognizer * _Nullable)doubleTapRecognizer;
@end

@class CAShapeLayer;

@interface UIView (SWIFT_EXTENSION(LiquidPlatformKit))
- (CAShapeLayer * _Nonnull)maskByRoundingCorners:(UIRectCorner)corners cornerRadii:(float)cornerRadii borderWidth:(float)borderWidth borderColor:(UIColor * _Nonnull)borderColor;
- (void)pinParentFull;
@end


@interface UIViewController (SWIFT_EXTENSION(LiquidPlatformKit))
- (void)safeAddChildViewController:(UIViewController * _Nonnull)viewController targetView:(UIView * _Nonnull)targetView;
- (void)safeRemoveChildViewController:(UIViewController * _Nonnull)viewController;
@end

#pragma clang diagnostic pop
